### PR TITLE
Rename "CascadeBot" to "Cascade"

### PR DESCRIPTION
**Pull request by binaryoverload**

### CODE REVIEW

**Comment by JamesHawkinss** [comment]
Was this discussed in a meeting?

**Comment by binaryoverload** [comment]
Nope, wondering if we should

**Comment by JamesHawkinss** [comment]
Perhaps. It's a big change to make, after all.

**Comment by Ikinon** [comment]
I don't mind, but can we at least make the "cascadebot" change to "cascade" in the wrapper as well if we're doing it here

**Comment by JamesHawkinss** [comment]
Waiting on meeting.

**Pull request closed without merging**
