### PR TITLE
Add sentry to the bot for reporting errors

### PR DESCRIPTION
**Pull request by binaryoverload**
Self explanatory really

### CODE REVIEW

**Comment by weeryan17** [comment]
have you tested this?

**Comment by binaryoverload** [comment]
There's no way I can test it currently but this is the exact way we did it on FlareBot so it'll work

**Comment by weeryan17** [comment]
We should set up a sentry account and test before we merge this, cause i know sentry has changed some of their stuff.

**Comment by binaryoverload** [comment]
I'll do that this evening then 👌

**Comment by binaryoverload** [comment]
@weeryan17 Fully tested, changed it to use an env variable as it works better with the logback appender.

**Pull request merged**
