### PR TITLE
Lombok!

### PR DESCRIPTION
**Pull request by binaryoverload**
# Pull request

 - [x] I have read and agreed to the [code of conduct](https://github.com/CascadeBot/CascadeBot/blob/master/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/CascadeBot/CascadeBot/blob/master/.github/CONTRIBUTING.md).
 - [x] What I'm implementing was assigned to me or was not being worked on and is a somewhat requested feature. For reference see our [GitHub projects](https://github.com/orgs/CascadeBot/projects).
 - [x] I have tested all of my changes.
 
## Added/Changed

Look here: #113

### CODE REVIEW

**Comment by weeryan17** [comment]
I'm going to do some messing around on my own before i review this so i know whats going on.

**Comment by binaryoverload** [comment]
Alrightly 👌 Make sure to get the Lombok plugin installed

**Comment by weeryan17** [comment]
Link please

**Comment by taydev** [comment]
https://plugins.jetbrains.com/plugin/6317-lombok

**Pull request merged**
