### PR TITLE
Docker!

### PR DESCRIPTION
**Pull request by TortleWortle**
# Pull request

 - [x] I have read and agreed to the [code of conduct](https://github.com/CascadeBot/CascadeBot/blob/master/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/CascadeBot/CascadeBot/blob/master/.github/CONTRIBUTING.md).
 - [x] What I'm implementing was assigned to me or was not being worked on and is a somewhat requested feature. For reference see our [GitHub projects](https://github.com/orgs/CascadeBot/projects).
 - [x] I have tested all of my changes.
 
## Added/Changed
Added a multi-stage dockerfile that builds a docker image

## Feature
Containers!

### CODE REVIEW

**Comment by weeryan17** [comment]
For now we have not decided if we will go with docker for running the bot or not so far now theirs not much point in this. I will re-open this if we do decide to go with docker.

**Comment by weeryan17** [comment]
jenkins approve

**Comment by weeryan17** [comment]
jenkins whitelist

**Comment by weeryan17** [comment]
Are you still interested in doing this? I know you where working on improving the docker file but its been a while.

**Comment by TortleWortle** [comment]
I remember there being some weird issue with maven offline-mode that prevented a more optimised version from working correctly (which would only affect subsequent builds), the Dockerfile still works but there are a few improvements that could be made:

- better usage of the build cache
- default config with a setup script to inject the most basic config variables from env (nice for quickly getting the bot started for testing)

**Comment by weeryan17** [comment]
> default config with a setup script to inject the most basic config variables from env (nice for quickly getting the bot started for testing)

Is their a way to specify variables for use in building an image? Cause the config has things like bot token that we definitely don't want to have public.

**Pull request closed without merging**
