### PR TITLE
✔ Alpha v0.1.9

### PR DESCRIPTION
**Pull request by weeryan17**
[changelog]
;f New commands
`;equalizer` - Adjust equalizer levels!
`;playtop` - Plays the song straight away.
`;queue move` - Moves a song within the queue.
`;queue remove` - Removes a song from the queue.
`;karaoke` - Lists the lyrics for a song as it plays!

`;page` - Easily jump to a page in a paged message.
`;remindme` - Ask the bot to remind you of a message!

`;welcome` - Allows you to create welcome messages.
`;goodbye` - Allows you to create goodbye messages.
`;autorole` - Automatically assigns roles to a user when they join the server.
`;filters` - Allows you to filter commands based on user, role or channel!

`;slowmode` - Sets an arbitrary slowmode for a channel.
`;tempslowmode` - Sets a slowmode temporarily and then reverts it.
`;mute` - Mutes a user.
`;unmute` - Unmutes a user.
`;tempmute` - Mutes a user temporarily.
`;tempban` - Bans a user temporarily.

`;purge user` - Now takes multiple users!

;f User Stuff
Localised colours
UI/UX Improvements (See PR [#189](https://github.com/CascadeBot/CascadeBot/issues/189))

;f Technical Stuff
Database Restructure
Move a good chunk over to Kotlin

;d We're excited to finally be updating the bot with a whole bunch of new features! After a long wait, we can finally push out new functionality to Cascade 🎉

Due to the massive rewrite of everything, there is probably a tad bit of buggage. As usual, please report any problems in the <#548975880924561409> channel!

To find the usage of a command, please use `;usage <command>` 😃

;t The long awaited Alpha update! 

;c green

### CODE REVIEW

**Comment by binaryoverload** [comment]
;preview

**Comment by binaryoverload** [comment]
;preview

**Comment by binaryoverload** [comment]
;preview

**Comment by binaryoverload** [comment]
;preview

**Comment by weeryan17** [comment]
;preview

**Review by binaryoverload — APPROVED** [review]

**Comment by weeryan17** [comment]
;publish

**Pull request merged**
