### PR TITLE
Cascade version 1.1! 🎉

### PR DESCRIPTION
**Pull request by binaryoverload**
# Pull request

 - [x] I have read and agreed to the [code of conduct](https://github.com/CascadeBot/CascadeBot/blob/master/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/CascadeBot/CascadeBot/blob/master/.github/CONTRIBUTING.md).
 - [x] What I'm implementing was assigned to me or was not being worked on and is a somewhat requested feature. For reference see our [GitHub projects](https://github.com/orgs/CascadeBot/projects).
 - [x] I have tested all of my changes.
 
## Added/Changed
 - Update to JDA 4 (This is my main reasoning for this PR)
 - Module errors now show by default!
 - Fix bugs
 - A bunch of small visual changes

### CODE REVIEW

**Comment by JamesHawkinss** [comment]
THIS IS EXCITING OOOO

**Comment by binaryoverload** [comment]
https://github.com/DV8FromTheWorld/JDA/releases/tag/v4.0.0

**Comment by binaryoverload** [comment]
jenkins build

**Comment by binaryoverload** [comment]
Just going to wait until I finalize the arg splitter and then I'll merge this

**Comment by binaryoverload** [comment]
jenkins build

**Pull request merged**
