### PR TITLE
Cat Command and Dog Command

### PR DESCRIPTION
**Pull request by JamesHawkinss**
# Pull request

 - [ ] I have read and agreed to the [CODE OF CONDUCT](https://github.com/CascadeBot/CascadeBot/blob/master/CODE_OF_CONDUCT.md).
 - [ ] What I'm implementing was assigned to me or was not being worked on and is a somewhat requested feature. For reference see our [trello](https://trello.com/b/gUQehy4l/bot).
 - [ ] I have tested all of my changes.
 - [ ] I have followed the style of the rest of the project.
 
## Added/Changed
What did you add and/or change for this.

## Feature
If this is a new feature, why should we add it to the bot.

### CODE REVIEW

**Comment by binaryoverload** [comment]
Can one of the admins verify this patch?

**Comment by binaryoverload** [comment]
add to whitelist

**Comment by binaryoverload** [comment]
ok to test

**Comment by binaryoverload** [comment]
I'm going to suggest merging these into 1 PetCommand with two aliases of `cat` and `dog`. You can check the trigger to see if they used `pet`, `cat` or `dog` as the command and change what to request appropriately. If it's pet, then it chooses either dog or cat randomly :P

**Comment by weeryan17** [comment]
I agree with binary on making it one command. this could also be a nice test of our sub command system.

**Comment by weeryan17** [comment]
Also why are you trying to merge into master

**Comment by weeryan17** [comment]
@JamesHawkinss re do your changes based of the dev branch please.

**Pull request closed without merging**
