### PR TITLE
Alpha Update

### PR DESCRIPTION
**Pull request by binaryoverload**
Changelog will be made soon

[changelog]
;t The first Alpha update!
;d  • We now have a `;seek` command to skip to a certain point in a song! 
 • Todo lists have arrived!
​ ​ ​ ​ 1. Create a todo-list with `;todo create`!
​ ​ ​ ​ 2. Add items to the todo-list with `;todo add`!
​ ​ ​ ​ 3. Send the todo-list to a channel using `;todo send`!
 • We now have support for Bandcamp! (If anyone uses Bandcamp 👀)

**This is the first update in our soon-to-be regular alpha updating schedule! The official version is `alpha-0.1.0`**

;f User experience changes
 • Tags are now case-insensitive!
 • Buttons will no longer display on a single page
 • There's now an option to cancel the action on any confirmation prompts
 • Search command has got proper titles!
 • We decided to be nice and give skip voting its own embed; equality and all!
 • You can now see who has requested those many many pictures of cats and dogs
 • The complete length of the queue is now displayed at the bottom of the queue

;f Bugs
 • Mention and ID parsing is now *hopefully* fully functional!
;c green

### CODE REVIEW

**Comment by mrjvs** [comment]
;preview

**Comment by binaryoverload** [comment]
;preview

**Comment by binaryoverload** [comment]
;preview

**Comment by binaryoverload** [comment]
;preview

**Comment by binaryoverload** [comment]
;preview

**Comment by weeryan17** [comment]
;preview

**Comment by binaryoverload** [comment]
;publish

**Pull request merged**
